export enum ActionType {
    GET_APP_CONFIG,
    SET_APP_CONFIG,
    GET_VIOLATION_ROWS,
    SET_VIOLATION_ROWS,
    SET_MSG_TIME,
    SET_FREQ,
    SET_MSG_ID,
    SET_IS_GEN_SEL,
    INIT_MSG_INSTRUCTIONS,
    SET_VOLT_VIOL_MSG,
    SET_LOAD_VIOL_MSG,
    SET_ZCV_VIOL_MSG,
    SET_SPL_EVNTS,
    SET_MSG_INSTRUCTIONS,
    SET_VIOL_TYPE,
    SAVE_VIOL_LOG
}