export enum ActionType {
    GET_APP_CONFIG,
    SET_APP_CONFIG,
    GET_VIOLATION_ROWS,
    SET_VIOLATION_ROWS,
    SET_MSG_TIME,
    SET_FREQ,
    SET_MSG_ID,
    SET_IS_GEN_SEL,
    INIT_MSG_INSTRUCTIONS,
    SET_MSG_INSTRUCTIONS,
    SET_VIOL_TYPE
}